### ISSUE TITLE
Compile Error with new openfl version

### ISSUE THREAD

**Issue by guifes** [HaxeFlixel/flixel-ui#133]
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:309: characters 3-7 : String should be openfl.text.TextFormatAlign
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:309: characters 3-7 : String should be openfl._legacy.text.TextFormatAlign
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:310: characters 3-7 : String should be openfl.text.TextFormatAlign
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:310: characters 3-7 : String should be openfl._legacy.text.TextFormatAlign
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:311: characters 3-7 : String should be openfl.text.TextFormatAlign
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:311: characters 3-7 : String should be openfl._legacy.text.TextFormatAlign
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:312: characters 3-7 : String should be openfl.text.TextFormatAlign
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:312: characters 3-7 : String should be openfl._legacy.text.TextFormatAlign
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:313: characters 3-10 : String should be openfl.text.TextFormatAlign
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:313: characters 3-10 : String should be openfl._legacy.text.TextFormatAlign
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:318: characters 2-25 : openfl.text.TextFormatAlign should be String
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FontDef.hx:318: characters 2-25 : openfl._legacy.text.TextFormatAlign should be String

actuate: 1.8.3 1.8.4 1.8.5 [1.8.6]
box2d: [1.2.3]
flixel-addons: git [dev:/usr/lib/haxe/lib/flixel-addons/git]
flixel-demos: git [dev:/usr/lib/haxe/lib/flixel-demos/git]
flixel-templates: [1.0.2]
flixel-tools: 1.0.5 1.1.0 [1.1.1]
flixel-ui: git [dev:/usr/lib/haxe/lib/flixel-ui/git]
flixel: 3.3.8 git [dev:/usr/lib/haxe/lib/flixel/git]
haxelib_client: 3.1.0-rc.4 3.2.0-rc.1 3.2.0-rc.2 [3.2.0-rc.3]
hxcpp: 3.2.102 [3.2.171] 3.2.37 3.2.81 3.2.94
layout: 1.2.0 [1.2.1]
lime-samples: 2.2.0 2.3.0 2.4.0 2.5.1 [2.6.0]
lime: 2.2.1 2.2.2 2.3.0 2.3.1 2.3.2 2.3.3 2.4.0 2.4.1 2.4.2 2.4.3 2.4.4 2.4.5 2.4.6 2.4.7 2.4.8 2.4.9 2.5.0 2.5.1 2.5.2 2.5.3 2.6.0 2.6.1 2.6.2 2.6.3 2.6.4 [2.6.6]
openfl-samples: 2.2.2 3.1.0 [3.3.0]
openfl: 2.2.8 3.0.0-beta.2 3.0.0-beta.3 3.0.1 3.0.2 3.0.3 3.0.4 3.0.5 3.0.6 3.0.8 3.1.0 3.1.1 3.1.2 3.1.3 3.1.4 3.2.0 3.2.1 3.2.2 3.3.0 3.3.1 3.3.2 3.3.3 3.3.4 3.3.5 [3.3.6]
polygonal-core: [1.0.4]
polygonal-ds: [1.4.1]
polygonal-printf: [1.0.2-beta]
swf: 1.8.0 1.8.1 1.8.2 1.8.4 1.8.5 1.8.6 1.8.7 1.8.8 1.8.9 1.9.0 1.9.1 2.0.0 2.0.1 2.0.2 2.0.3 [2.0.4]

**Comment by larsiusprime** [comment]
Which target? Flash, CPP, both of them?

**Comment by guifes** [comment]
All of them, even neko

**Comment by larsiusprime** [comment]
Hmm, I'll look into it. I didn't have this issue but maybe I'm not running the latest OpenFL.

**Comment by Gama11** [comment]
This is the same thing that has been causing the travis failures.

**Comment by larsiusprime** [comment]
Interesting; I've been confused because when I click through the travis builds say they're failing, but the logs show nothing but successful tests! Maybe I've been reading them wrong.

**Comment by larsiusprime** [comment]
@guifes are you using the latest version of flixel? It says you're using the git version, but I think the latest git version has 3.3.11 instead of 3.3.8 in the haxelib.json ?

**Comment by guifes** [comment]
That 3.3.8 was the previous version I had before using de dev branch. It's listed, but I'm not using it. Tried to delete it but the problem persists.

**Comment by larsiusprime** [comment]
Ah I see. I think this is just a result of me testing mostly in -Dnext and not -Dlegacy. I should have this fixed soon, hopefully.

**Comment by larsiusprime** [comment]
@guifes:

Just pushed a potential fix. Can you try the "lars_latest" branch?

**Comment by guifes** [comment]
I'll try it as soon as I can! I'll report back here. ;)

**Comment by guifes** [comment]
It compiled, but now I have this error for a code that was previously working fine.

Invalid operation (>>)
Called from flixel/text/FlxText.hx line 684
Called from flixel/addons/ui/BorderDef.hx line 26
Called from flixel/addons/ui/FlxUI.hx line 2458
Called from flixel/addons/ui/FlxUI.hx line 1797
Called from flixel/addons/ui/FlxUI.hx line 881
Called from flixel/addons/ui/FlxUI.hx line 803
Called from flixel/addons/ui/FlxUIState.hx line 369
Called from flixel/addons/ui/FlxUIState.hx line 190
Called from a C function
Called from state/MenuState.hx line 40
Called from flixel/FlxGame.hx line 616
Called from flixel/FlxGame.hx line 701
Called from flixel/FlxGame.hx line 681
Called from flixel/FlxGame.hx line 523
Called from openfl/_legacy/events/EventDispatcher.hx line 98
Called from a C function
Called from openfl/_legacy/display/DisplayObject.hx line 161
Called from a C function
Called from openfl/_legacy/display/DisplayObjectContainer.hx line 286
Called from openfl/_legacy/display/Stage.hx line 1103
Called from openfl/_legacy/display/Stage.hx line 351
Called from openfl/_legacy/display/Stage.hx line 1084
Called from openfl/_legacy/display/Stage.hx line 430
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by larsiusprime** [comment]
Shucks, I'll try again tomorrow.

**Comment by MSGhero** [comment]
I get error messages like that in neko when I attempt to use undefined variables. Even ints need to be initialized to 0 or else you'll get an error like this.

The error is occurring when FlxColor attempts to get its alpha value by bit shifting `this` by 24, which implies `this` is undefined. Idk if that's the actual issue or a result of the issue.

**Comment by guifes** [comment]
Just tested cpp build, worked fine.

**Comment by guifes** [comment]
Any updates on this? Finally managed to get hate working again on El Captain. Still got the same error on neko and now my cpp build is giving me this:

> ui/FlxUIText.cpp -o/Users/guilhermefernandes/Workspace/Haxe/Primeira/export/mac64/cpp/obj/obj/darwin64/c6d1c639_FlxUIText.o
Error: ./src/flixel/addons/ui/FlxUITooltipManager.cpp:533:10: error: no member named 'set_x' in 'flixel::addons::ui::interfaces::IFlxUIButton_obj'
                                btn->set_x(tmp8);
                                ~~~  ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp:537:10: error: no member named 'set_y' in 'flixel::addons::ui::interfaces::IFlxUIButton_obj'
                                btn->set_y(tmp9);
                                ~~~  ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp:613:17: error: no member named 'set_x' in 'flixel::addons::ui::interfaces::IFlxUIButton_obj'
                                tmp14->btn->set_x(tmp15);
                                ~~~~~~~~~~  ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp:623:17: error: no member named 'set_y' in 'flixel::addons::ui::interfaces::IFlxUIButton_obj'
                                tmp18->btn->set_y(tmp19);
                                ~~~~~~~~~~  ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp:819:10: error: no member named 'set_x' in 'flixel::addons::ui::interfaces::IFlxUIButton_obj'
                                btn->set_x(tmp16);
                                ~~~  ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp:823:10: error: no member named 'set_y' in 'flixel::addons::ui::interfaces::IFlxUIButton_obj'
                                btn->set_y(tmp17);
                                ~~~  ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp:827:10: error: no member named 'set_visible' in 'flixel::addons::ui::interfaces::IFlxUIButton_obj'
                                btn->set_visible(tmp18);
                                ~~~  ^
7 errors generated.

**Comment by Gama11** [comment]
@guifes That error is caused by a bug on the Haxe dev branch (see https://github.com/HaxeFoundation/haxe/issues/4343). Try with Haxe 3.2.0.

**Comment by larsiusprime** [comment]
Seeing as this seems to be a Haxe dev issue and not the fault of flixel-ui, I'm closing it for now?

**Comment by IBwWG** [comment]
Does flixel-ui work with Haxe 3.3.0-rc.1?

**Comment by Gama11** [comment]
Yes, No, Yes.
